paperwork:
  image: conoria/paperwork
  links:
    - paperwork-db:paperwork-db
  environment:
    - PAPERWORK_URL=paperwork.example.com

paperwork-db:
  image: mariadb
  volumes:
    - pwdb:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=paperwork
    - MYSQL_DATABASE=paperwork
    - MYSQL_USER=paperwork
    - MYSQL_PASSWORD=paperwork

